# Generated by Django 3.1.6 on 2021-02-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='attribution',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='audience',
            field=models.CharField(choices=[('K12', 'K-12'), ('HIE', 'Higher Education'), ('PFT', 'Professional Training'), ('NSP', 'Not Specific'), ('OTH', 'Other')], default='K12', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='author_bio',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='contact',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='devices',
            field=models.CharField(choices=[('DOL', 'Desktop or Laptop Computer'), ('CON', 'Chromebook or Other Netbook'), ('IPD', 'iPad'), ('ATB', 'Android Tablet'), ('IPH', 'iPhone'), ('APH', 'Android Phone'), ('RSP', 'Raspberry Pi'), ('MCC', 'Microcontroller(s)'), ('OTH', 'Other')], default='OTH', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='language',
            field=models.CharField(default='English', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='organization',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='requirements',
            field=models.CharField(default='stuff', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='requires_signup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('PA', 'Platform or App'), ('CU', 'Curriculum'), ('TC', 'Tutorial or Course'), ('BK', 'Book'), ('WE', 'Worked Example'), ('DC', 'Documentation'), ('OT', 'Other')], default='OT', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='standards',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
