# Generated by Django 3.1.6 on 2021-03-01 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20210225_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='license',
            field=models.CharField(default='MIT', max_length=200),
            preserve_default=False,
        ),
    ]
