# Generated by Django 3.1.6 on 2021-03-01 22:51

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_resource_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='organization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='populations',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('PRI', 'Primary'), ('SEC', 'Secondary '), ('COL', 'College/University'), ('ADU', 'Adult/Professional'), ('OTH', 'Other'), ('NON', 'None')], default='OTH', max_length=23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='psf_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='roles',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('STD', 'Student'), ('PES', 'Primary/Secondary Educator (school setting)'), ('PEO', 'Primary/Secondary Educator (out of school setting)'), ('TF', 'Teaching Faculty (post-secondary)'), ('AEB', 'Adult Educator or Trainer (bootcamp, industry)'), ('AEC', 'Adult Educator or Trainer (teacher PD, coaching)'), ('CUR', 'Curriculum or Product Developer'), ('VOL', 'Education Volunteer'), ('RES', 'Researcher'), ('MNT', 'Mentor'), ('INP', 'Industry Professional (Tech/Software/CS)'), ('EDV', 'Educational program developer'), ('PRT', 'Parent supporting education'), ('OTH', 'Other')], default='OTH', max_length=54),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='work_with_underrepresented_groups',
            field=models.BooleanField(default=False),
        ),
    ]
