# Generated by Django 3.1.6 on 2021-03-01 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_auto_20210301_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='work_with_underrepresented_groups',
            new_name='underrep',
        ),
    ]
