# Generated by Django 3.1.10 on 2021-05-11 14:10

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_resource_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='author_bio',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='standards',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='url',
        ),
        migrations.AddField(
            model_name='resource',
            name='python_related',
            field=models.CharField(choices=[('PS', 'Python Specific - part or all of resource is Python specific'), ('LA', 'Language Agnostic - can be used with any programming language'), ('UN', 'Unkown')], default='UN', help_text='Select the option that best describes this resource.', max_length=2),
        ),
        migrations.AddField(
            model_name='resource',
            name='url1',
            field=models.CharField(default='bleh', help_text='You must link at least one resource.', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='url2',
            field=models.CharField(blank=True, help_text='Optional additional url related to the same resource', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='url3',
            field=models.CharField(blank=True, help_text='Optional additional url related to the same resource', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='url_description1',
            field=models.CharField(blank=True, help_text='Use this field, if you are including multiple urls', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='url_description2',
            field=models.CharField(blank=True, help_text='Use this field, if you are including multiple urls', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='url_description3',
            field=models.CharField(blank=True, help_text='Use this field, if you are including multiple urls', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='use_type',
            field=models.CharField(choices=[('OSP', 'Open Source Project - accepts contributions'), ('OER', 'Open Education Resource - ok to distribute and/or revise/remix'), ('FRE', 'Free Resource - free to use'), ('IUM', 'Freemium - significant portion of resource free to use'), ('PAI', 'Paid - costs money to access this resource'), ('UNK', 'Bleh')], default='UN', help_text='Select the use type that best describes this resource.', max_length=3),
        ),
        migrations.AlterField(
            model_name='resource',
            name='attribution',
            field=models.CharField(default='bleh', help_text='What person or organization created this resource?', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resource',
            name='audience',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('K12', 'K-12'), ('HIE', 'Higher Education'), ('PFT', 'Professional Training'), ('NSP', 'Not Specific'), ('OTH', 'Other')], help_text="Select 'not specific' for resources for any or all audiences.", max_length=3),
        ),
        migrations.AlterField(
            model_name='resource',
            name='contact',
            field=models.CharField(blank=True, help_text='Not for display, What is the best way to reach you if we have questions about this submission?', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.CharField(default='bleh', help_text='Add a description of this resource. (max 500 characters)', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resource',
            name='devices',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('DOL', 'Desktop or Laptop Computer'), ('CON', 'Chromebook or Other Netbook'), ('IPD', 'iPad'), ('ATB', 'Android Tablet'), ('IPH', 'iPhone'), ('APH', 'Android Phone'), ('RSP', 'Raspberry Pi'), ('MCC', 'Microcontroller(s)'), ('OTH', 'Other')], help_text='Which devices are compatible with this resource', max_length=3),
        ),
        migrations.AlterField(
            model_name='resource',
            name='language',
            field=models.CharField(blank=True, help_text='What language/s are the written materials available in?', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='license',
            field=models.CharField(blank=True, help_text="What is the copyright license type? Type 'unknown' if the license type is not available.", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='requires_signup',
            field=models.CharField(choices=[('CA', 'Must create an account'), ('PE', 'Must provide email address'), ('NR', 'No sign up requirement')], help_text='Are users required to create an account or provide their email address to access this resource?', max_length=3),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('PA', 'Platform or App'), ('CU', 'Curriculum'), ('TC', 'Tutorial or Course'), ('BK', 'Book'), ('WE', 'Worked Example'), ('DC', 'Documentation'), ('OT', 'Other')], help_text='Select all that apply.', max_length=3),
        ),
        migrations.AlterField(
            model_name='resource',
            name='title',
            field=models.CharField(help_text='What is the name of the resource', max_length=200),
        ),
    ]
