# Generated by Django 3.1.6 on 2021-05-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_auto_20210512_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='url1',
            field=models.URLField(help_text='You must link at least one resource.'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='url2',
            field=models.URLField(blank=True, help_text='Optional additional url related to the same resource', null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='url3',
            field=models.URLField(blank=True, help_text='Optional additional url related to the same resource', null=True),
        ),
    ]
