# Generated by Django 3.1.6 on 2021-05-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0009_auto_20210516_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='resource',
        ),
        migrations.AddField(
            model_name='resource',
            name='author',
            field=models.ManyToManyField(to='resources.Author'),
        ),
    ]
