# Generated by Django 3.1.6 on 2021-05-16 18:33

from django.db import migrations


def force_url_objects(apps, schema_editor):
    Resource = apps.get_model("resources", "Resource")

    Resource.objects.all().update()


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0009_auto_20210516_1108'),
    ]

    operations = [
        migrations.RunPython(force_url_objects, reverse_code=migrations.RunPython.noop)
    ]
