# Generated by Django 3.1.6 on 2021-05-20 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0011_auto_20210520_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='language',
        ),
        migrations.AddField(
            model_name='resourcestatus',
            name='sequence',
            field=models.IntegerField(default=1),
        ),
    ]
