# Generated by Django 3.1.6 on 2021-06-08 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0014_auto_20210607_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='status',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='resources.resourcestatus'),
        ),
    ]
